[package]
name = "pcre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.137"
regex = "1.7.0"


[build-dependencies]
cc = "1.0"
pkg-config = "0.3.26"
